### ISSUE TITLE
set and replace txn doesn't fail (as expected) ...

### ISSUE THREAD

**Issue by norton** [hibari/gdss-brick#6]
Generally speaking, the expectation for Hibari microtransactions is to be all or nothing.  If one of the operations fails, the remaining operations should have no effect.  Unfortunately, it has been confirmed that set and replace operations do not follow this expectation with certain types of timestamp inputs.

A newly added (manual) unit test illustrates the unexpected behavior:

    https://github.com/hibari/gdss-admin/blob/dev/test/eunit/brick_txn_tests.erl

Further analysis is required to better understand the possible impacts to Hibari's application callers.

**Comment by tatsuya6502** [comment]
Changing the milestone from v0.3 to v0.1.11

**Comment by tatsuya6502** [comment]
Reviewed and looks good to me.

Also, I found those commits were already merged into master at Hibari v0.1.10 release (gdss-brick 0.1.6.1). I updated v0.1.10 and v0.1.11 release notes to record this fact. https://github.com/hibari/hibari/commit/2622ed801831195feb7a3c995c98691ea37bc980
